# paste config here
language: cpp
sudo: required

os:
- linux
- osx


compiler:
- gcc
- clang

addons:
apt:
  packages:
  - libhdf5-serial-dev
  - libopenmpi-dev
  - python-dev
  - python-h5py
  - python-matplotlib
  - python-numpy
  - python-scipy
  - libeigen3-dev
  - doxygen
  - graphviz
homebrew:
  packages:
  - openmpi
  - doxygen
  - libomp
  - graphviz
  
install: true

script:
-  export INSTALL_DIR=$HOME/root_install
-  cd $TRAVIS_BUILD_DIR/libcntr
-  mkdir build && cd build
-  gcc -v
-  mpicc -v
-  clang -v
-  which clang
-  if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake .. -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_CXX_FLAGS="-std=c++11" -Domp=ON -Dmpi=ON -Dhdf5=ON -DBUILD_DOC=ON;  fi
-  if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake .. -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_CXX_FLAGS="-std=c++11" -Domp=OFF -Dmpi=ON -Dhdf5=ON -DBUILD_DOC=ON;  fi
-  make   && make test

