# paste config here
language: cpp
sudo: required

os:
- linux

dist: xenial

compiler:
- gcc
- clang

before_install:
-  if ["$TRAVIS_OS_NAME" = "linux"];  then sudo apt-get update;  fi
-  if ["$TRAVIS_OS_NAME" = "linux"];  then sudo apt-get install -y --allow-unauthenticated  libhdf5-serial-dev libopenmpi-dev python-dev python-h5py python-matplotlib  python-numpy python-scipy libeigen3-dev doxygen graphviz;  fi

install: true

script:
-  export INSTALL_DIR=$HOME/root_install
-  cd $TRAVIS_BUILD_DIR/libcntr
-  mkdir build && cd build
-  cmake .. -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_CXX_FLAGS="-std=c++11" -Domp=ON -Dmpi=ON -Dhdf5=ON -DBUILD_DOC=ON
-  make   && make test

